#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

n=0
m=1

while [ $n -le 12 ]; do
	echo "Hour: $n"
	while [ $m -le 59 ]; do
		echo $m
		m=$((m+1))
	done
	m=$((1))
	n=$((n+1))
done
